AutoBarn/AutoBarn.WebUI/Areas/Admin/Controllers/BlockDateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoBarn.WebUI.Data;
using AutoBarn.WebUI.Data.Entities;

namespace AutoBarn.WebUI.Areas.Admin.Controllers
{
    public class BlockDateController : Controller
    {
        private readonly IRepository<BlockDate> _blockDateRepository;

        public BlockDateController(IRepository<BlockDate> blockDateRepository)
        {
            _blockDateRepository = blockDateRepository;
        }

        // GET: Admin/BlockDate
        public ActionResult Index()
        {
            var blockDates = _blockDateRepository.GetAll().Where(x => x.Date >= DateTime.Now);
            return View(blockDates);
        }

        public ActionResult Add(DateTime? NewBlockDate)
        {
            if (NewBlockDate != null)
            {
                var newDate = new BlockDate {Date = NewBlockDate.Value};
                _blockDateRepository.Add(newDate);
                _blockDateRepository.Commit();
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var blockDate = _blockDateRepository.Find(id);

            if (blockDate != null)
            {
                _blockDateRepository.Delete(blockDate);
                _blockDateRepository.Commit();
            }
            

            return RedirectToAction("Index");
        }
    }
}

AutoBarn/AutoBarn.WebUI/Controllers/BlockDateController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using AutoBarn.WebUI.Data;
using AutoBarn.WebUI.Data.Entities;

namespace AutoBarn.WebUI.Controllers
{
    [Authorize]
    public class BlockDateController : Controller
    {
        private readonly IRepository<BlockDate> _blockDateRepository;

        public BlockDateController(IRepository<BlockDate> blockDateRepository)
        {
            _blockDateRepository = blockDateRepository;
        }

        // GET: Admin/BlockDate
        public ActionResult Index()
        {
            var blockDates = _blockDateRepository.GetAll().Where(x => x.Date >= DateTime.Now);
            return View(blockDates);
        }

        public ActionResult Add(DateTime? newBlockDate)
        {
            if (newBlockDate != null)
            {
                var newDate = new BlockDate {Date = newBlockDate.Value};
                _blockDateRepository.Add(newDate);
                _blockDateRepository.Commit();
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var blockDate = _blockDateRepository.Find(id);

            if (blockDate != null)
            {
                _blockDateRepository.Delete(blockDate);
                _blockDateRepository.Commit();
            }
            

            return RedirectToAction("Index");
        }
    }
}

AutoBarn/AutoBarn.WebUI/Areas/Admin/Views/BlockDate/Index.cshtml
@model IEnumerable<AutoBarn.WebUI.Data.Entities.BlockDate>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col"></div>
</div>

<div class="row">
    <div class="col s2 m2">&nbsp;</div>
    <div class="col s8 m8">

        <h2>Block Dates From Booking Form</h2>
        <p>These dates will appear block out on the booking form calendar.</p>

        
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Date)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.Date.ToShortDateString()
                    </td>
                    <td>
                        @Html.ActionLink("Delete", "Delete", new {id = item.Id})
                    </td>
                </tr>
            }

            @using (Html.BeginForm("Add", "BlockDate", FormMethod.Post))
            {
                <tr>
                    <td><input type="date" name="NewBlockDate" /></td>
                    <td><input type="submit" value="Add"/></td>
                </tr>
            }
           

        </table>


    </div>
</div>