AutoBarn/AutoBarn.WebUI/Controllers/BookingController.cs
namespace AutoBarn.WebUI.Controllers
{
    using System;
    using System.Data.Entity;
    using System.Linq;
    using System.Runtime.Caching;
    using System.Web.Mvc;
    using AutoBarn.WebUI.Data;
    using AutoBarn.WebUI.Data.Entities;
    using AutoBarn.WebUI.Models;
    using AutoBarn.WebUI.Services;

    public class BookingController : Controller
    {
        private readonly IRepository<Make> _makeRepository;
        private readonly IRepository<Model> _modelRepository;
        private readonly IRepository<Service> _serviceRepository;
        private readonly IRepository<Contact> _contactRepository;
        private readonly IRepository<Booking> _bookingRepository;
        private readonly IBookingEmailService _bookingEmailService;
        private readonly IRepository<BlockDate> _blockDateRepository;

        public BookingController(IRepository<Make> makeRepository
            , IRepository<Model> modelRepository
            , IRepository<Service> serviceRepository
            , IRepository<Contact> contactRepository
            , IRepository<Booking> bookingRepository
            , IRepository<BlockDate> blockDateRepository
            , IBookingEmailService bookingEmailService)
        {
            _blockDateRepository = blockDateRepository;
            _bookingEmailService = bookingEmailService;
            _bookingRepository = bookingRepository;
            _makeRepository = makeRepository;
            _modelRepository = modelRepository;
            _serviceRepository = serviceRepository;
            _contactRepository = contactRepository;
        }

        public JsonResult Makes()
        {
            var makes = _makeRepository.GetAll().ToList();
            return Json(makes, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Models(int id)
        {
            var models = _modelRepository.GetAll().Where(x => x.Make.Id == id).ToList();
            return Json(models, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Services(int id)
        {
            var services = _serviceRepository.GetAll().Where(x => x.Model.Id == id).ToList();
            return Json(services, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Service(int id)
        {
            var services = _serviceRepository.GetAll().First(x => x.Id == id);
            return Json(services, JsonRequestBehavior.AllowGet);
        }

        // GET: Booking
        public ActionResult New(int makeId = 0, int modelId = 0, int serviceId = 0)
        {
            ViewBag.CustomerReviews = MemoryCache.Default.Get("Review") as string;
            var model = new BookingViewModel
            {   
                SelectedModel = new Model { Id=0, Make = new Make { Id=0} },
                SelectedService = new Service { Id = 0},
                Makes = _makeRepository.GetAll().ToList(),
                Models = _modelRepository.GetAll().Where(x=>x.Make.Id== makeId).ToList(),
                Services = _serviceRepository.GetAll().Where(x=>x.Model.Id== modelId).ToList()
            };

            if (makeId > 0)
            {
                var vehicleModel = _modelRepository.GetAll()
                    .Include(x => x.Make)
                    .Include(m => m.Services)
                    .First(x => x.Id == modelId);

                model.SelectedModel = vehicleModel;
                model.SelectedService = vehicleModel.Services.First(x => x.Id == serviceId);
            }

            return View(model);
        }

        public JsonResult BlockDates()
        {
            var queryDate = DateTime.Now.AddDays(-1);
            var format = "yyyy-MM-dd";
            var dates = _blockDateRepository.GetAll().ToList().Select(x => x.Date.ToString(format));
            
            return Json(dates, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Save a new booking submission from the Booking form page
        /// </summary>
        /// <param name="model">The Booking view model.</param>
        /// <returns></returns>
        public ActionResult Save(NewBookingViewModel model)
        {
            if (model.BookingDate == null)
            {
                throw new Exception("The booking date was null");
            }

            // obfuscate the identity fields for contacts now
            // we shouldn't store user data anymore as part of the
            // new GDPR rules, more work involved if we want to start
            // doing things with the users data
            var contact = new Contact
            {
                Firstname = "XXXXXXX",
                Lastname = "XXXXXXX",
                Email = "XXXXXXX",
                Telephone = "XXXXXXX",
                ModelId = model.SelectedModel.Id,
                Registration = "XXXXXXXXXX"
            };

            _contactRepository.Add(contact);
            _contactRepository.Commit();
            
            var booking = new Booking
            {
                ModelId = model.SelectedModel.Id,
                ServiceId = model.SelectedService.Id,
                Date = model.BookingDate,
                Contact = contact,
                Notes = string.IsNullOrEmpty(model.Notes) ? string.Empty : model.Notes
            };

            _bookingRepository.Add(booking);

            _bookingRepository.Commit();
           
            _bookingEmailService.SetHtmlString(Server.MapPath("~/App_Data/bookingconfirmation.html"));
            _bookingEmailService.SetPlaceholders(booking.Id, model.Contact.Firstname, model.Contact.Registration, booking.Date, booking.Notes);
            _bookingEmailService.CreateMessage(model.Contact.Email);
            _bookingEmailService.CreateAutoBarnMessage(model.Contact.Firstname, model.Contact.Lastname, model.Contact.Email, model.Contact.Telephone);
            _bookingEmailService.SendEmail();

            return RedirectToAction("ThankYou", new { id = booking.Id});
        }

        public ActionResult ThankYou(int id = 0)
        {
            ViewBag.CustomerReviews = MemoryCache.Default.Get("Review") as string;
            var booking = _bookingRepository.GetAll()
                .Include(x => x.Model)
                .Include(x => x.Model.Make)
                .Include(x => x.Service)
                .Include(x => x.Contact).FirstOrDefault(x => x.Id == id);

            return View(booking);
        }
    }
}

AutoBarn/AutoBarn.WebUI/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Caching;
using System.Web;
using System.Web.Mvc;
using AutoBarn.WebUI.Services.Filters;

namespace AutoBarn.WebUI.Controllers
{
    public class GalleryController : Controller
    {
        // GET: Gallery
        public ActionResult Index()
        {
            ViewBag.CustomerReviews = MemoryCache.Default.Get("Review") as string;
            return View();
        }
    }
}

AutoBarn/AutoBarn.WebUI/Controllers/GermanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Caching;
using System.Web;
using System.Web.Mvc;
using AutoBarn.WebUI.Services.Filters;

namespace AutoBarn.WebUI.Controllers
{
    public class GermanController : Controller
    {
        // GET: German
        public ActionResult Brands(string heading = "")
        {
            var dictionary = new Dictionary<string, string>
            {
                {"VW_Audi_Seat_And_Skoda_Servicing", "VW, Audi, Seat & Skoda Servicing"},
                {"BMW_Servicing_specialists", "BMW Servicing specialists"},
                {"Mercedes_Servicing_specialists", "Mercedes Servicing specialists"},
                {"Motorhome_Servicing_And_Class_7_MOTs", "Motorhome Servicing & Class 7 MOT's"}
            };




            ViewBag.CustomerReviews = MemoryCache.Default.Get("Review") as string;
            ViewBag.BrandHeading = dictionary.ContainsKey(heading) ? dictionary[heading] : string.Empty;
            return View();
        }

        [ActionName("VW_Audi_Seat_And_Skoda_Servicing")]
        public ActionResult VwAudiSeatSkoda()
        {
            return View();
        }

        [ActionName("BMW_Servicing_specialists")]
        public ActionResult Bmw()
        {
            return View();
        }

        [ActionName("Mercedes_Servicing_specialists")]
        public ActionResult Mercedes()
        {
            return View();
        }

        [ActionName("Motorhome_Servicing_And_Class_7_MOTs")]
        public ActionResult MotorHome()
        {
            return View();
        }
    }
}

AutoBarn/AutoBarn.WebUI/Controllers/PegasusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutoBarn.WebUI.Controllers
{
    public class PegasusController : Controller
    {
        // GET: Pegasus
        public ActionResult Index()
        {
            return View();
        }

        [ActionName("Automatic-Electric-Side-Steps")]
        public ActionResult SideSteps()
        {
            return View();
        }

        [ActionName("Hard-Tops")]
        public ActionResult HardTops()
        {
            return View();
        }

        [ActionName("Top-Up-Covers")]
        public ActionResult TopUpCovers()
        {
            return View();
        }

        [ActionName("Sports-Lids")]
        public ActionResult SportsLids()
        {
            return View();
        }

        public ActionResult Accessories()
        {
            return View();
        }
    }
}

AutoBarn/AutoBarn.WebUI/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title | Service & MOT | Car service | Engine Remapping Waterlooville | Car MOT | Hampshire car service | Waterlooville car MOT | Waterloovile MOT and servicing |</title>
    <meta name="description" content="Auto-Barn are a family owned garage able repair, MOT and service all motor vehicles upto and including 3.5tonne commercial vehicles. Based in Waterlooville, Hampshire" />
    <meta name="keywords" content="Car service , Engine Remapping Waterlooville , Car MOT , Hampshire car service , Waterlooville car MOT , Waterloovile MOT and servicing, Auto-Barn Motor Services, Autobarn, Auto-Barn, autobahn, MOT, Service, Waterlooville Garages, Hampshire garages, Car Service, Car Repair, Car MOT" />

    @Styles.Render("~/Content/materialize")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("style", required: false)
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400' rel='stylesheet' type='text/css'/>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Crimson+Text"/>
    @*<link rel="stylesheet" href="~/Content/bootstrap-image-gallery.min.css">*@

    @Scripts.Render("~/bundles/calltracking")
    @Scripts.Render("~/bundles/googleanalytics")
</head>
<body style="">
   <div class="top-line">
    <div class="row instant-quote">
        <div class="col s12 center-align">
            <span class="glyphicon glyphicon-phone" aria-hidden="true"></span>
            Call us now on <span class="mediahawkNumber1263 mhMobile">02392 592010</span>
        </div>
    </div>
    <div class="row instant-quote">
        <div class="col s12 center-align">
            <span><a href="@Url.Action("New", "Booking")">INSTANT ONLINE QUOTE</a></span>
        </div>
  </div>
</div>

<nav id="nav-bar" role="navigation">
    <div class="nav-wrapper container">
        <a href="@Url.Action("Index", "Home")"><img src="~/Content/Images/auto-barn-logo.png" class="brand-logo"/></a>
        <ul class="right hide-on-med-and-down">
            <li><a href="@Url.Action("New", "Booking")">MAKE A BOOKING</a></li>
            <li>
                <a href="@Url.Action("ServiceMot", "Home")" data-activates='dropdown1' class='dropdown-button btn'>Service & MOT</a>
                <!-- Dropdown Structure -->
                <ul id='dropdown1' class='dropdown-content'>
                    <li><a href="@Url.Action("VW_Audi_Seat_And_Skoda_Servicing", "German")" style="color: #3878E2;">VW, Audi, Seat & Skoda Servicing</a></li>
                    <li><a href="@Url.Action("BMW_Servicing_specialists", "German")" style="color: #3878E2;">BMW Servicing specialists</a></li>
                    <li><a href="@Url.Action("Mercedes_Servicing_specialists", "German")" style="color: #3878E2;">Mercedes Servicing specialists</a></li>
                    <li><a href="@Url.Action("Motorhome_Servicing_And_Class_7_MOTs", "German")" style="color: #3878E2;">Motorhome Servicing & Class 7 MOT's</a></li>
                </ul>
            </li>
            <li><a href="@Url.Action("Index", "Gallery")">GALLERY</a></li>
            <li><a href="@Url.Action("Recovery", "Home")">BREAKDOWN SERVICE</a></li>
            <li><a href="@Url.Action("Ramp", "Home")">RAMP HIRE</a></li>
            <li><a href="@Url.Action("Contact", "Home")">CONTACT US</a></li>
        </ul>
        <ul id="nav-mobile" class="side-nav">
            <li><a href="@Url.Action("New", "Booking")">Make a booking</a></li>
            <li>
                <a href="@Url.Action("ServiceMot", "Home")" data-activates='dropdown2' class='dropdown-button btn'>Service & MOT</a>
                <!-- Dropdown Structure -->
                <ul id='dropdown2' class='dropdown-content'>
                    <li><a href="@Url.Action("VW_Audi_Seat_And_Skoda_Servicing", "German")">VW, Audi, Seat & Skoda</a></li>
                    <li><a href="@Url.Action("BMW_Servicing_specialists", "German")">BMW</a></li>
                    <li><a href="@Url.Action("Mercedes_Servicing_specialists", "German")">Mercedes Servicing</a></li>
                    <li><a href="@Url.Action("Motorhome_Servicing_And_Class_7_MOTs", "German")">Motorhome & Class 7</a></li>
                </ul>
            </li>
            <li><a href="@Url.Action("Index", "Gallery")">Gallery</a></li>
            <li><a href="@Url.Action("Recovery", "Home")">Breakdown Service</a></li>
            <li>
                <a href="@Url.Action("ServiceMot", "Home")" data-activates='dropdown4' class='dropdown-button btn'>Pickup & 4X4 Accessories</a>
                <ul id="dropdown4" class="dropdown-content">
                    <li><a href="@Url.Action("Automatic-Electric-Side-Steps", "Pegasus")" style="color: #3878E2;">Electric Side Steps</a></li>
                    <li><a href="@Url.Action("Hard-Tops", "Pegasus")" style="color: #3878E2;">Hard Tops</a></li>
                    <li><a href="@Url.Action("Top-Up-Covers", "Pegasus")" style="color: #3878E2;">Top Up Covers</a></li>
                    <li><a href="@Url.Action("Sports-Lids", "Pegasus")" style="color: #3878E2;">Sports Lids</a></li>
                    <li><a href="@Url.Action("Accessories", "Pegasus")" style="color: #3878E2;">Accessories</a></li>
                </ul>
            </li>
            <li><a href="@Url.Action("Contact", "Home")">Contact us</a></li>
        </ul>
        <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
</nav>


@RenderBody()

<footer class="page-footer autobarn">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="autobarn">About Us</h5>
                <p>Autobarn Motor Services was founded in 2010. The 3 members of staff have a combined trade experience in excess of 30 years. After working for a number of years for Mercedes-Benz, BMW and VW the trio decided to have a go themselves and haven't looked back since.</p>

            </div>
            <div class="col l3 s12">
                <h5 class="autobarn">Contact Us</h5>
                <ul>
                    <li>Auto-Barn Motor Services Ltd</li>
                    <li>The Barn</li>
                    <li>259 Lovedean Lane</li>
                    <li>Waterlooville</li>
                    <li>Hampeshire</li>
                    <li>PO8 9RX</li>
                    <li><span class="mediahawkNumber1263 mhMobile">02392 592010</span></li>
                </ul>
            </div>
            <div class="col l3 s12">
                <h5 class="autobarn">Opening Hours</h5>
                <ul>
                    <li><a href="#!">Monday to Friday 08:00 - 17:30</a></li>
                    <li><a href="#!">Saturday 08:30 - 12:30</a></li>
                    <li><a href="#!">Sunday Closed</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container center-align">
            <a href="https://www.facebook.com/Auto-barn-Motor-Services-Ltd-487008848048938/?fref=ts">
                <img src="~/Content/Images/Social/FB-FindUsonFacebook-online-144.png"/>
            </a>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container center-align">
            Copyright Auto-Barn Motor Services 2015. All rights reserved. <a href="https://4plus12.co.uk/websites">Want a website like this?</a>
        </div>
    </div>
</footer>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/materialize")
@RenderSection("scripts", required: false)

</body>
</html>

AutoBarn/AutoBarn.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title | Service & MOT | Car service | Engine Remapping Waterlooville | Car MOT | Hampshire car service | Waterlooville car MOT | Waterloovile MOT and servicing |</title>
    <meta name="description" content="Auto-Barn are a family owned garage able repair, MOT and service all motor vehicles upto and including 3.5tonne commercial vehicles. Based in Waterlooville, Hampshire" />
    <meta name="keywords" content="Car service , Engine Remapping Waterlooville , Car MOT , Hampshire car service , Waterlooville car MOT , Waterloovile MOT and servicing, Auto-Barn Motor Services, Autobarn, Auto-Barn, autobahn, MOT, Service, Waterlooville Garages, Hampshire garages, Car Service, Car Repair, Car MOT" />

    @Styles.Render("~/Content/materialize")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("style", required: false)
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400' rel='stylesheet' type='text/css' />
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Crimson+Text" />
    @*<link rel="stylesheet" href="~/Content/bootstrap-image-gallery.min.css">*@


    @Scripts.Render("~/bundles/googleanalytics")
    @Scripts.Render("~/bundles/calltracking")
</head>
<body style="">
    <div class="top-line">
        <div class="row">
            <div class="col s2">&nbsp;</div>
            <div class="col s8 right-align" id="instant-quote">
                <span class="glyphicon glyphicon-phone" aria-hidden="true"></span>
                <span>Call us now on <span class="mediahawkNumber1263">02392 592010</span> |</span> <a href="@Url.Action("New", "Booking")">INSTANT ONLINE QUOTE</a>
                <a href="@Url.Action("Contact", "Home")">CONTACT US</a>
            </div>
            <div class="col s2">&nbsp;</div>
        </div>
    </div>

    <nav id="nav-bar" role="navigation">
        <div class="nav-wrapper container">
            @*<a id="logo-container" href="#" class="brand-logo">AUTO-BARN MOTOR SERVICES LTD</a>*@
            <a href="@Url.Action("Index", "Home")" id="logo-container"><img src="~/Content/Images/auto-barn-logo.png" class="brand-logo" /></a>
            <ul class="right hide-on-med-and-down">
                <li><a href="@Url.Action("New", "Booking")">MAKE A BOOKING</a></li>
                <li>
                    <a href="@Url.Action("ServiceMot", "Home")" data-activates='dropdown1' class='dropdown-button btn'>SERVICE & MOT</a>
                    <!-- Dropdown Structure -->
                    <ul id='dropdown1' class='dropdown-content'>
                        <li><a href="@Url.Action("VW_Audi_Seat_And_Skoda_Servicing", "German")" style="color: #3878E2;">VW, Audi, Seat & Skoda Servicing</a></li>
                        <li><a href="@Url.Action("BMW_Servicing_specialists", "German")" style="color: #3878E2;">BMW Servicing specialists</a></li>
                        <li><a href="@Url.Action("Mercedes_Servicing_specialists", "German")" style="color: #3878E2;">Mercedes Servicing specialists</a></li>
                        <li><a href="@Url.Action("Motorhome_Servicing_And_Class_7_MOTs", "German")" style="color: #3878E2;">Motorhome Servicing & Class 7 MOT's</a></li>
                    </ul>
                </li>
                @*<li><a href="@Url.Action("Index", "Gallery")">GALLERY</a></li>*@
                <li><a href="@Url.Action("Ramp", "Home")">RAMP HIRE</a></li>
                <li><a href="@Url.Action("Recovery", "Home")">BREAKDOWN SERVICE</a></li>
                <li>
                    <a href="@Url.Action("Automatic-Electric-Side-Steps", "Pegasus")" data-activates='dropdown2' class='dropdown-button btn'>PICKUP & 4X4</a>
                    <ul id="dropdown2" class="dropdown-content">
                        <li><a href="@Url.Action("Automatic-Electric-Side-Steps", "Pegasus")" style="color: #3878E2;">Automatic Electric Side Steps</a></li>
                        <li><a href="@Url.Action("Hard-Tops", "Pegasus")" style="color: #3878E2;">Hard Tops</a></li>
                        <li><a href="@Url.Action("Top-Up-Covers", "Pegasus")" style="color: #3878E2;">Top Up Covers</a></li>
                        <li><a href="@Url.Action("Sports-Lids", "Pegasus")" style="color: #3878E2;">Sports Lids</a></li>
                        <li><a href="@Url.Action("Accessories", "Pegasus")" style="color: #3878E2;">Accessories</a></li>
                    </ul>
                </li>
            </ul>


            <ul id="nav-mobile" class="side-nav">
                <li><a href="@Url.Action("New", "Booking")">Make a booking</a></li>
                <li>
                    <a href="@Url.Action("ServiceMot", "Home")" data-activates='dropdown3' class='dropdown-button btn'>SERVICE & MOT</a>
                    <!-- Dropdown Structure -->
                    <ul id='dropdown3' class='dropdown-content'>
                        <li><a href="@Url.Action("VW_Audi_Seat_And_Skoda_Servicing", "German")">VW, Audi, Seat & Skoda Servicing</a></li>
                        <li><a href="@Url.Action("BMW_Servicing_specialists", "German")">BMW Servicing</a></li>
                        <li><a href="@Url.Action("Mercedes_Servicing_specialists", "German")">Mercedes Servicing</a></li>
                        <li><a href="@Url.Action("Motorhome_Servicing_And_Class_7_MOTs", "German")">Motorhome Servicing & Class 7 MOT's</a></li>
                        <li><a href="@Url.Action("Automatic_Electric_Side_Steps", "Pegasus")">Automatic Electric Side Steps</a></li>
                    </ul>
                </li>
                <li><a href="@Url.Action("Index", "Gallery")">Gallery</a></li>
                <li><a href="@Url.Action("Ramp", "Home")">Ramp</a></li>
                <li><a href="@Url.Action("Recovery", "Home")">Breakdown Service</a></li>
                <li>
                    <a href="@Url.Action("Automatic-Electric-Side-Steps", "Pegasus")" data-activates='dropdown4' class='dropdown-button btn'>Pickup & 4X4</a>
                    <ul id="dropdown4" class="dropdown-content">
                        <li><a href="@Url.Action("Automatic-Electric-Side-Steps", "Pegasus")" style="color: #3878E2;">Automatic Electric Side Steps</a></li>
                        <li><a href="@Url.Action("Hard-Tops", "Pegasus")" style="color: #3878E2;">Hard Tops</a></li>
                        <li><a href="@Url.Action("Top-Up-Covers", "Pegasus")" style="color: #3878E2;">Top Up Covers</a></li>
                        <li><a href="@Url.Action("Sports-Lids", "Pegasus")" style="color: #3878E2;">Sports Lids</a></li>
                        <li><a href="@Url.Action("Accessories", "Pegasus")" style="color: #3878E2;">Accessories</a></li>
                    </ul>
                </li>
                <li><a href="@Url.Action("Contact", "Home")">Contact us</a></li>
            </ul>
            <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
        </div>
    </nav>


    @RenderBody()

    <footer class="page-footer autobarn">
        <div class="container">
            <div class="row">
                <div class="col l6 s12">
                    <h5 class="autobarn">About Us</h5>
                    <p>Autobarn Motor Services was founded in 2010. The 3 members of staff have a combined trade experience in excess of 30 years. After working for a number of years for Mercedes-Benz, BMW and VW the trio decided to have a go themselves and haven't looked back since.</p>

                </div>
                <div class="col l3 s12">
                    <h5 class="autobarn">Contact Us</h5>
                    <ul>
                        <li>Auto-Barn Motor Services Ltd</li>
                        <li>The Barn</li>
                        <li>259 Lovedean Lane</li>
                        <li>Waterlooville</li>
                        <li>Hampeshire</li>
                        <li>PO8 9RX</li>
                        <li><span class="mediahawkNumber1263">02392 592010</span></li>
                    </ul>
                </div>
                <div class="col l3 s12">
                    <h5 class="autobarn">Opening Hours</h5>
                    <ul>
                        <li><a href="#!">Monday to Friday 08:00 - 17:30</a></li>
                        <li><a href="#!">Saturday 08:30 - 12:30</a></li>
                        <li><a href="#!">Sunday Closed</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container center-align">
                <a href="https://www.facebook.com/Auto-barn-Motor-Services-Ltd-487008848048938/?fref=ts">
                    <img src="~/Content/Images/Social/FB-FindUsonFacebook-online-144.png" />
                </a>
            </div>
            <div class="container center-align">
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container center-align">
                Copyright Auto-Barn Motor Services 2015. All rights reserved. <a href="https://4plus12.co.uk/websites">Want a website like this?</a>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/materialize")
    @RenderSection("scripts", required: false)

    <script>
        $(document).ready(function(){
          $('.dropdown-button').dropdown({
              inDuration: 300,
              outDuration: 225,
              constrain_width: false, // Does not change width of dropdown to that of the activator
              hover: true, // Activate on hover
              gutter: ($('.dropdown-content').width()*0)/4.5 + 2, // Spacing from edge
              belowOrigin: true, // Displays dropdown below the button
              alignment: 'left' // Displays dropdown with edge aligned to the left of button
            }
          );

        });
    </script>

</body>
</html>

AutoBarn/AutoBarn.WebUI/Views/Shared/_OtherMakes.cshtml
<div style="background-color: #F4F4F4; margin-bottom: -0px; margin-top: -120px;">
    <div class="row"></div>

    <div class="row">
        <div class="col s2 m3">&nbsp;</div>

        <div class="col s12 m6">
            <h2>Other makes</h2>
            <p>
                Although we are the German auto specialists, we can of course work on any make and model of car and vans

                up to 3.5 tonne. We also have a large ramp that enables us to work on large motorhomes. If you have any

                questions relating to any other models or would like an estimate for any repairs please call us on <strong><span class="mediahawkNumber1263">02392 592010</span></strong>
                or send an email to <a href="mailto:info@autobarnmotorservices.co.uk">info@autobarnmotorservices.co.uk</a>
            </p>
        </div>
        <div class="col s2 m2">&nbsp;</div>
    </div>

</div>